cat ~/.local/state/caelestia/sequences.txt 2>/dev/null

set fish_greeting

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    set EDITOR hx

    # Zoxide
    zoxide init fish | source

    # Abbreviations

    # Aliases
    alias nr 'sudo nixos-rebuild switch --flake'
    alias qsd 'nix develop ~/dix#quickshell'
    alias rsd 'nix develop ~/dix#rustlings'
    alias ls 'eza --icons'
    alias hjem-pure 'systemd-tmpfiles --user --create'

    # Interactive shell initialisation
    if test "$TERM" != dumb
        /nix/store/9fnhax88khgd917p1mnnb649a1fpr0jq-starship-1.23.0/bin/starship init fish | source

    end

    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION no-rc
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/awesome/.local/share/fish/home-manager_generated_completions" $post
    end

end
