// Generated by Home Manager.



user_pref("browser.newtab.url", "about:blank");
user_pref("browser.startup.homepage", "about:blank");
user_pref("dom.security.https_only_mode", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("ui.systemUsesDarkTheme", 2);



